version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pharmacy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pharmacy
      SPRING_DATASOURCE_USERNAME: praveenkumar
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: praveenkumar
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pharmacy
