#server:
#  port: 8081
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/yourDatabase
#    username: root
#    password: secret
#    driver-class-name: org.postgresql.Driver
#
#logging:
#  level:
#    org.springframework: INFO
#    com.example: DEBUG
#
#app:
#  title: "Pharmacy Management"
#  description: "Initial pharmacy management application."
