#  server:
#   port: 9090

#  spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/pharmacy
#     username: praveenkumar
#     password: admin
#     driver-class-name: org.postgresql.Driver
#   jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: true
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQLDialect

#  logging:
#   level:
#     org.springframework: INFO
#     com.example: DEBUG

#  app:
#   title: "Pharmacy Management"
#   description: "Initial pharmacy management application."
